[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = .
lib_deps =
  ArduinoJson
  TinyGPSPlus
  Adafruit Unified Sensor
  Adafruit MPU6050
  marcoschwartz/LiquidCrystal_I2C
 